### ISSUE TITLE
Invalid PDB id message for 4no4

### ISSUE THREAD

**Issue by josemduarte** [selcukorkmaz/BET#1]
The entry exists and was released in 2014. Not sure why the bioassembly tool says it's an invalid pdb id.

**Comment by josemduarte** [comment]
Same for 4mec.

**Comment by selcukorkmaz** [comment]
When I first created the PDB entries list, I only used PDB entries which have primary citations. Both cases do not have a published paper. I have added both cases to the list, so you can evaluate them using the tool. I will create a new PDB list for the new version.
